sudo: false
language: node_js
node_js:
  - '6'
  - '8'
  - '10'
  - '12'
before_install:
  - npm i npminstall@3.x -g
install:
  - npminstall
script:
  - npm run ci
after_script:
  - npminstall codecov && codecov
